### ISSUE TITLE
Tasklist

### ISSUE THREAD

**Issue by patmagauran** [patmagauran/i915ovmfPkg#1]
- [ ] Fix Thunderbolt Reset Problem
- [x] Generate new EDID / Clock values for my setup and GVT-D
- [x] Compare changes in EDID/Clock to determine generational/hw differences
- [x] Find the correct interface to determine EDID information
- [x] Implement EDID reading
- [x] Implement Clock value reading
- [x] Implement eDP Support
- [x] Extend eDP to DP as well
- [x] Better Error Handling
- [x] Code Cleanup
- [x] Dynamically choose which output to use
- [ ] Rewrite HDMI EDID / GMBUS Code

**Comment by Midou36O** [comment]
Is the project abondonned?
