### ISSUE TITLE
i7 8086k kernel panics with test-gvt-d.sh / FwCfg issues(Status 3)

### ISSUE THREAD

**Issue by aspenluxxxy** [patmagauran/i915ovmfPkg#10]
Tried with both pre-built and compiling it myself.

(Linux 5.9.11)

![Untitled-1](https://user-images.githubusercontent.com/65794972/101232040-4ae0f200-367d-11eb-9fa8-86710ad7b31f.jpg)

**Comment by aspenluxxxy** [comment]
![image](https://user-images.githubusercontent.com/65794972/101232541-233f5900-3680-11eb-986e-3d7a116369a0.jpeg)

After installing intel-ucode and setting the max pstate to 0

**Comment by RotatingFans** [comment]
Is this for GVT-G or GVT-D? How are you running the vm?

**Comment by aspenluxxxy** [comment]
GVT-d, and I was using the [test-gvt-d.sh](https://github.com/RotatingFans/i915ovmfPkg/blob/master/test-gvt-d.sh) script included with the repo (obviously with the `WORKSPACE` and `PCIID` to changed to match my setup)

**Comment by RotatingFans** [comment]
Interesting. Here is the last line we know runs. https://github.com/RotatingFans/i915ovmfPkg/blob/fce6788882734eb4fc5b16c729250cdb1da7a6ae/i915_display.c#L165

I can't imagine any of those lines causing a hardware error based on what I have read in the PRMs. We could try to do a print after each line to see how far we get in the execution of that function.

Also if you are interested. Here is the line in the linux kernel driver that does what we are doing here: https://elixir.bootlin.com/linux/v5.9.12/source/drivers/gpu/drm/i915/display/intel_color.c#L480

Possibly may be beneficial to try the steps listed here to get more information: https://askubuntu.com/questions/454775/debug-faulty-hardware

**Comment by aspenluxxxy** [comment]
According to some googling, the error is related to [power management](https://bugzilla.kernel.org/show_bug.cgi?id=103351).

I will attempt to get more info, though. Perhaps just straight up trying to run a Windows VM via libvirt will yield more success?

**Comment by aspenluxxxy** [comment]
Nope, libvirt + passing through iGPU results in my PC locking up with the reset button not working, very likely same/similar panic.

Tried upgrading my BIOS to latest, which didn't help any.

**Comment by ninele7** [comment]
Have i5 10400 with exactly the same problem. Getting panic and PC not responding to reset button.

**Comment by RotatingFans** [comment]
Could I get some information:
- What host OS & Version?
- SSH?
- QEMU Version?
- Desktop / Laptop?
- Displays connected?
- Other GPUS?
- Other system specs/info

**Comment by ninele7** [comment]
* Manjaro testing (end of november)
* SSH and TTY
* QEMU Version: 5.10
* Desktop
* 1920x1080 displayport connected to iGPU
* Also rx 580 in system with another connected display
Gpu to pass is UHD 630 (8086:9bc8) integrated in i5 10400

**Comment by RotatingFans** [comment]
Could you try with this rom(Added some extra logging). Also, try adding `-d out_asm -d guest_errors -D debugLog.log` to the qemu and retrieving the log file. 

I think there may be issues when running on a desktop system rather than a laptop. Unfortunately I do not have any intel desktops to test with.

[i915ovmf.zip](https://github.com/RotatingFans/i915ovmfPkg/files/5654528/i915ovmf.zip)

**Comment by aspenluxxxy** [comment]
@RotatingFans output logs were empty, probably cuz the full CPU/kernel crash doesn't let the disk sync

i got this though

![Untitled](https://user-images.githubusercontent.com/65794972/101393150-9faa8580-3894-11eb-9b0f-cea4e2ea70de.jpg)

**Comment by RotatingFans** [comment]
One thing I have noticed when debugging this software is that QEMU outputs the text in such a way that it gets overwritten. This is why I use PuTTY to run and read the output of the applications. I have not figured out the option that allows for this to happen, but PuTTy will write spaces rather than overwriting the screen. 

I am pretty sure this is happening because the next line after DPLL 1 is Locked should be another print in all cases. And you also had the error occur at a different spot earlier.

@aspenluxxxy could you try using [putty](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) or if that is not an option, using a terminal program that does not erase content on the screen. See here for what I mean: https://documentation.help/PuTTY/config-erasetoscrollback.html  I don't know if this will work or not because of the kernel panic.

**Comment by aspenluxxxy** [comment]
@RotatingFans 
[putty.log](https://github.com/RotatingFans/i915ovmfPkg/files/5655600/putty.log)

**Comment by RotatingFans** [comment]
Unfortunately it did get cut off. I encountered this type of issue when I was developing. The only solution I found was to progressively comment out lines until it didn't crash.(Unless your pc has a serial port, then maybe that would work, idk) Theoretically, considering the correct lines are commented, we won't cause any new panics, just prevent the actual display output. If you are up to it, I can write up a guide on what lines I recommend commenting and in what order. You would of course have to run from that compiled version.

**Comment by aspenluxxxy** [comment]
@RotatingFans sure

**Comment by RotatingFans** [comment]
Actually, after taking a closer look at the log file, it isn't properly setting up the memory management, which leads to a host of other problems throughout the code. Try this rom(it adds a debug statement that should help us determine what it can't setup): 
[i915ovmf-2.zip](https://github.com/RotatingFans/i915ovmfPkg/files/5655782/i915ovmf-2.zip)

**Comment by aspenluxxxy** [comment]
@RotatingFans 
[putty.log](https://github.com/RotatingFans/i915ovmfPkg/files/5656023/putty.log)

**Comment by RotatingFans** [comment]
@aspenluxxxy This tells me that the code cannot find the intel opregion or bdsmSize files that should be provided by QEMU. This could be due to a number of reasons, and I do not know how to get that information out of QEMU. See here for possible failure points: https://github.com/qemu/qemu/blob/269ff671c593379378c5cf5ea3bddd7909dd3333/hw/vfio/igd.c#L367 Maybe one of those errors has appeared in your jorunalctl or flashed on screen?

You may be able to try adding `x-igd-opregion=on` to the device options for the intel gpu. I do not know what this would do with our setup.

**Comment by RotatingFans** [comment]
Also see: https://github.com/qemu/qemu/blob/master/docs/igd-assign.txt
Theoretically this operates in Legacy Mode.

**Comment by aspenluxxxy** [comment]
```
vfio 0000:00:02.0: does not support requested IGD OpRegion feature: No such device
```

**Comment by aspenluxxxy** [comment]
i'd be willing to recompile qemu to try stuff if needed

**Comment by RotatingFans** [comment]
Perhaps try booting with the iGPU as the boot gpu. I wonder if since you have another gpu, your bios doesn't properly copy the opregion so QEMU doesn't either. 

If you can figure out which option enables the logging of those report_error lines within QEMU or just in general, please do so. I would rather find the most direct solution rather than any workarounds(See below)

I also want to state that we can manually patch these files through, by using the  `-fw_cfg name=XXXXX,file=XXXXX` QEMU Flag. We look for the two separate files referenced in https://github.com/qemu/qemu/blob/master/docs/igd-assign.txt
So if you dump the opRegion and create the bdsmSize file, you can manually pass them through and hopefully it should work. 

I believe the [intel-gpu-tools repo](https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/tree/tools) has some tools that can dump the raw opregion to a file.

**Comment by aspenluxxxy** [comment]
```
OpRegion Header:
	sign:	IntelGraphicsMem
	size:	0x00000008
	over:	0x02000000
	sver:	
	vver:	
	gver:	
	mbox:	0x0000001f
	dmod:	0x00000000
	pcon:	0x00000183
	dver:	9

OpRegion Mailbox 1: Public ACPI Methods:
	drdy:	0x00000001
	csts:	0x00000000
	cevt:	0x00000000
	didl:
		didl[0]:	0x00000300
		didl[1]:	0x00000301
		didl[2]:	0x00000302
		didl[3]:	0x00000303
		didl[4]:	0x00000000
		didl[5]:	0x00000000
		didl[6]:	0x00000000
		didl[7]:	0x00000000
	cpdl:
		cpdl[0]:	0x00000000
		cpdl[1]:	0x00000000
		cpdl[2]:	0x00000000
		cpdl[3]:	0x00000000
		cpdl[4]:	0x00000000
		cpdl[5]:	0x00000000
		cpdl[6]:	0x00000000
		cpdl[7]:	0x00000000
	cadl:
		cadl[0]:	0x00000300
		cadl[1]:	0x00000301
		cadl[2]:	0x00000302
		cadl[3]:	0x00000303
		cadl[4]:	0x00000000
		cadl[5]:	0x00000000
		cadl[6]:	0x00000000
		cadl[7]:	0x00000000
	nadl:
		nadl[0]:	0x00000000
		nadl[1]:	0x00000000
		nadl[2]:	0x00000000
		nadl[3]:	0x00000000
		nadl[4]:	0x00000000
		nadl[5]:	0x00000000
		nadl[6]:	0x00000000
		nadl[7]:	0x00000000
	aslp:	0x00000000
	tidx:	0x00000000
	chpd:	0x00000001
	clid:	0x00000003
	cdck:	0x00000000
	sxsw:	0x00000000
	evts:	0x00000000
	cnot:	0x00000000
	nrdy:	0x00000000
	did2:
		did2[0]:	0x00000000
		did2[1]:	0x00000000
		did2[2]:	0x00000000
		did2[3]:	0x00000000
		did2[4]:	0x00000000
		did2[5]:	0x00000000
		did2[6]:	0x00000000
	cpd2:
		cpd2[0]:	0x00000000
		cpd2[1]:	0x00000000
		cpd2[2]:	0x00000000
		cpd2[3]:	0x00000000
		cpd2[4]:	0x00000000
		cpd2[5]:	0x00000000
		cpd2[6]:	0x00000000

OpRegion Mailbox 2: Software SCI Interface (SWSCI):
	scic:	0x00000020
	parm:	0x00000000
	dslp:	0x00000000

OpRegion Mailbox 3: BIOS to Driver Notification (ASLE):
	ardy:	0x00000001
	aslc:	0x00000000
	tche:	0x00000002
	alsi:	0x00000000
	bclp:	0x000000ff
	pfit:	0x80000006
	cblv:	0x80000064
	bclm:
		bclm[0]:	0x8000 (  0% -> 0x00)
		bclm[1]:	0x8a19 ( 10% -> 0x19)
		bclm[2]:	0x9433 ( 20% -> 0x33)
		bclm[3]:	0x9e4c ( 30% -> 0x4c)
		bclm[4]:	0xa866 ( 40% -> 0x66)
		bclm[5]:	0xb27f ( 50% -> 0x7f)
		bclm[6]:	0xbc99 ( 60% -> 0x99)
		bclm[7]:	0xc6b2 ( 70% -> 0xb2)
		bclm[8]:	0xd0cc ( 80% -> 0xcc)
		bclm[9]:	0xdae5 ( 90% -> 0xe5)
		bclm[10]:	0xe4ff (100% -> 0xff)
		bclm[11]:	0x0000
		bclm[12]:	0x0000
		bclm[13]:	0x0000
		bclm[14]:	0x0000
		bclm[15]:	0x0000
		bclm[16]:	0x0000
		bclm[17]:	0x0000
		bclm[18]:	0x0000
		bclm[19]:	0x0000
	cpfm:	0x00000000
	epfm:	0x00000000
	plut header:	0x00
	plut identifier: 00 00 00 00 00 00 00 00 00 00
	plut:
		plut[0]:	00 00 00 00 00 00 00 
		plut[1]:	00 00 00 00 00 00 00 
		plut[2]:	00 00 00 00 00 00 00 
		plut[3]:	00 00 00 00 00 00 00 
		plut[4]:	00 00 00 00 00 00 00 
		plut[5]:	00 00 00 00 00 00 00 
		plut[6]:	00 00 00 00 00 00 00 
		plut[7]:	00 00 00 00 00 00 00 
		plut[8]:	00 00 00 00 00 00 00 
	pfmb:	0x00000000
	ccdv:	0x00000000
	pcft:	0x0000003e
	srot:	0x00000000
	iuer:	0x00000000
	fdss:	00 00 00 00 00 00 00 00 
	fdsp:	0x00000000
	stat:	0x00000000
	rvda:	0x0000000000000000
	rvds:	0x00000000

OpRegion Mailbox 4: Video BIOS Table (VBT):
	product string:	$VBT SKYLAKE        
	(use intel_vbt_decode to decode the VBT)

OpRegion Mailbox 5: BIOS to Driver Notification Extension:
	phed:	0x00000000
	bddc:
		bddc[0x00]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0x10]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0x20]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0x30]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0x40]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0x50]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0x60]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0x70]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0x80]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0x90]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0xa0]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0xb0]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0xc0]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0xd0]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0xe0]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
		bddc[0xf0]:	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
```

**Comment by aspenluxxxy** [comment]
> If you can figure out which option enables the logging of those report_error lines within QEMU or just in general

https://github.com/qemu/qemu/blob/master/util/qemu-error.c#L275-L289
```
/*
 * Print an error message to current monitor if we have one, else to stderr.
 * Format arguments like sprintf().  The resulting message should be
 * a single phrase, with no newline or trailing punctuation.
 * Prepend the current location and append a newline.
 * It's wrong to call this in a QMP monitor.  Use error_setg() there.
 */
void error_report(const char *fmt, ...)
{
    va_list ap;

    va_start(ap, fmt);
    vreport(REPORT_TYPE_ERROR, fmt, ap);
    va_end(ap);
}
```

**Comment by RotatingFans** [comment]
I will write up a workaround for this tomorrow. Hopefully it should work. I will also add better error handling for this error. Ideally, the rom should exit with an error instead of continuing and causing other issues and possible memory corruption.

@aspenluxxxy Interesting. When you run it without x-igd-opregion, does QEMU print anything before the driver starts. Perhaps to the dmesg? You may want to use the -S option, so that the driver doesn't start and no kernel panics occur. Qemu should have initialized the fwCFG files by that point.

**Comment by aspenluxxxy** [comment]
@RotatingFans nothing in dmesg but i got this ![image](https://user-images.githubusercontent.com/65794972/101436925-1b302500-38dd-11eb-9c66-bfb3fb43c88e.jpeg)

**Comment by RotatingFans** [comment]
Could you page up? If you need, possibly take a video and try to pause it. I want to see what happens right after the command is loaded but before the driver is loaded.

**Comment by aspenluxxxy** [comment]
I sadly couldn't reproduce the stack trace printing to the monitor.

**Comment by RotatingFans** [comment]
Here is the workaround: https://github.com/RotatingFans/i915ovmfPkg/wiki/Qemu-FwCFG-Workaround. Hopefully that works.

**Comment by aspenluxxxy** [comment]
That worked! Thank you.

**Comment by aspenluxxxy** [comment]
@RotatingFans update: no crashing, and Windows in the VM detects a second display when the Intel iGPU driver is installed, but no output whatsoever.

**Comment by RotatingFans** [comment]
That tells me that it is running in UPT mode rather than Legacy. @aspenluxxxy can you try setting the intel gpu as the host boot gpu. The test-gvt-d script should unbind it for you. It seems that QEMU may not enable legacy mode if it isn't the boot gpu(or if the bios neglected some setup b/c it isn't booting it). See https://github.com/intel/gvt-linux/issues/19

**Comment by aspenluxxxy** [comment]
@RotatingFans ![image](https://user-images.githubusercontent.com/65794972/101540970-c1783b00-396e-11eb-9bdf-5430215d7937.jpeg)

**Comment by aspenluxxxy** [comment]
wait why was the dGPU input showing that???

**Comment by RotatingFans** [comment]
At what point did was that displayed? And by dGPU you mean the other one not being passed through, correct?

**Comment by aspenluxxxy** [comment]
@RotatingFans after booting a VM, iGPU was the boot GPU, and yeah the non-passed-through GPU displayed that. Everything was fine after a reboot, so it's not damage or anything.

**Comment by RotatingFans** [comment]
Perhaps that when the display-manager was shut down it was left in an unclean state. I don't know why that would happen, and is out of the control of this software. The script simply stops display-manager.service. My personal opinion is that it looks like some memory corruption or artifacting on the dGPU. However, there shouldn't be a reason that this software causes that. 

Did setting the iGPU as boot allow the windows VM to work?

**Comment by aspenluxxxy** [comment]
> Did setting the iGPU as boot allow the windows VM to work?

nope. i suspected i had a bad cable at first, but my main (non-virtualized) Windows install shows the iGPU as a second monitor correctly.

**Comment by RotatingFans** [comment]
If you use the test-gvt-d.sh script, there should be a log file in i915_simple. Could you upload that?

**Comment by aspenluxxxy** [comment]
@RotatingFans 
`SetupFwcfgStuff: etc/igd-bdsm-size: invalid fw_cfg size: 4`

**Comment by RotatingFans** [comment]
Oops. Accidentally made the file 4 bytes instead of 8. Try replacing bdsmSize.bin with this one: https://github.com/RotatingFans/i915ovmfPkg/raw/18d354a4636ab30d54ce429c219f16755c55701e/bdsmSize.bin

**Comment by aspenluxxxy** [comment]
@RotatingFans we're back to panicking 
[putty.log](https://github.com/RotatingFans/i915ovmfPkg/files/5669063/putty.log)

**Comment by my33love** [comment]
Add own VBT and GOP   drivers to the OVMF:
https://projectacrn.github.io/latest/tutorials/gpu-passthru.html
Add the IgdAssignment to the OVMF:
https://github.com/nchevsky/pve-edk2-firmware

OVMF UEFI firmware for Proxmox VE with added support for IGD passthrough with output to external displays (VFIO's `x-igd-opregion=on`), as well as the ability to boot macOS virtual machines.

**Comment by RotatingFans** [comment]
@aspenluxxxy here is a new ROM to try(More logging). Could you also run intel_vbt_decode op.rom where op.rom is the opregion you extracted earlier. Also let me know what you are using to connect the gpu to a monitor(HDMI, DP, etc.). It seems that it can't set the output path which probably causes some bad configuration in the registers. I also modified the rom to exit when it can't set an output Path.
[i915ovmf.zip](https://github.com/RotatingFans/i915ovmfPkg/files/5674219/i915ovmf.zip)

**Comment by aspenluxxxy** [comment]
@RotatingFans my monitor only has 1 DP input, and my motherboard has no HDMI whatsoever, so I was using a DP->HDMI cable, which i'd imagine works because back when I had an Oculus Rift, the adapter worked perfectly for that.

**Comment by RotatingFans** [comment]
@my33love Interesting. I think the part of that solution that may be difficult for users is obtaining the drivers. That hypervisor also seems to fit a different need than QEMU. If you would wish to continue this discussion, please create a new issue so we don't clutter this one.

**Comment by RotatingFans** [comment]
@aspenluxxxy I will have to read about how adapters work with regards to the display driver. For now, just upload the vbt decode and new rom output when possible.

**Comment by aspenluxxxy** [comment]
@RotatingFans
[opregion_vbt_decoded.txt](https://github.com/RotatingFans/i915ovmfPkg/files/5674544/opregion_vbt_decoded.txt)

**Comment by aspenluxxxy** [comment]
Also, output with new ROM:
[serial.log](https://github.com/RotatingFans/i915ovmfPkg/files/5674570/serial.log)

**Comment by RotatingFans** [comment]
So passive DP->HDMI adapters should work pretty easily as long as well assume that the port is HDMI. Active ones may behave differently. 
Assuming yours is passive(the most common), we are getting stuck reading the EDID. The best reason I can come up with is that the current gmbus/EDID code for HDMI is very hacky. Its possible that rewriting it could get it to work. 
Another issue is that for some reason, the DP output is not being tried. 
Until I can try to rewrite the gmbus code(Which I should do anyway), @aspenluxxxy could you possibly try a direct DP connection, Rather than using the adapter. That would at least verify if there is a general problem or more specific to the usage of an adapter.

**Comment by aspenluxxxy** [comment]
@RotatingFans direct DP connection: 
[serial.log](https://github.com/RotatingFans/i915ovmfPkg/files/5675138/serial.log)

**Comment by RotatingFans** [comment]
Try this with the direct connection. If that works try the adapter. Apparently EDK2 Booleans have undefined behavior for values other than one or zero.

[i915ovmf.zip](https://github.com/RotatingFans/i915ovmfPkg/files/5675888/i915ovmf.zip)

**Comment by aspenluxxxy** [comment]
Ooh, this is a new one:
[serial.log](https://github.com/RotatingFans/i915ovmfPkg/files/5676241/serial.log)

**Comment by my33love** [comment]
@RotatingFans vbt&gop can dump very easy from bios.bin with UEFITool. 
https://www.win-raid.com/t5360f13-EFI-LAN-BIOS-Intel-GopDriver-modules.html
https://www.win-raid.com/t905f13-Guide-Transfer-of-specific-Intel-OROM-VBIOS-and-GOP-VBT-settings-by-using-Intel-BMP-tool.html

**Comment by RotatingFans** [comment]
@aspenluxxxy Try this one. Another small mistake. Only did displayport training for eDP, not DP as well.
[i915ovmf.zip](https://github.com/RotatingFans/i915ovmfPkg/files/5681523/i915ovmf.zip)

**Comment by aspenluxxxy** [comment]
No output seemingly, but the log looks more promising: 
[serial.log](https://github.com/RotatingFans/i915ovmfPkg/files/5681568/serial.log)

**Comment by RotatingFans** [comment]
I found one misconfiguration in the registers that I fixed and a couple that weren't printed to screen so I added in that logging. 
[i915ovmf.zip](https://github.com/RotatingFans/i915ovmfPkg/files/5683467/i915ovmf.zip)

**Comment by aspenluxxxy** [comment]
@RotatingFans 
```
i915: Port Is Connected!
i915: failed to Set OutputPath
i915: DisplayInit Error. 14
```
[serial.log](https://github.com/RotatingFans/i915ovmfPkg/files/5683680/serial.log)

**Comment by aspenluxxxy** [comment]
actually i tried again after re-setting my port, didn't get tht error, but it still didn't work:
[serial.log](https://github.com/RotatingFans/i915ovmfPkg/files/5683682/serial.log)

**Comment by RotatingFans** [comment]
Fixed one more small difference. 
[i915ovmf.zip](https://github.com/RotatingFans/i915ovmfPkg/files/5684053/i915ovmf.zip)

**Comment by aspenluxxxy** [comment]
I feel like I'm doing something wrong, the log looks fairly nominal?: [serial.log](https://github.com/RotatingFans/i915ovmfPkg/files/5684103/serial.log)

**Comment by RotatingFans** [comment]
I checked all of the registers and everything seems correct. I can think of two things to be sure of:

- Make sure you can get output over that cable normally.
- Make sure the script doesn't timeout before the display has time to wake up.

Otherwise, I can do a little more reading in the intel Reference Manuals just to be sure. It is possible a single bit in a register could be incorrectly configured, causing no output.

**Comment by aspenluxxxy** [comment]
Cable/output is fine on a normal install of Windows.

An emulated install of Windows with the ROM and iGPU passed through will actually show it _as a second big ol' monitor_ when plugged in, but nothing still gets output at all.

**Comment by RotatingFans** [comment]
This tells me that it isn't running in Legacy mode, but instead is running in Universal Passthrough Mode. This seems to be the case with multiple people and I do not know why it is behaving different on my machine.

**Comment by RotatingFans** [comment]
I am going to try to read through the QEMU code to figure this out.

**Comment by RotatingFans** [comment]
Try adding this to the iGPU line in the test script: bus=pci.0,addr=0x2

**Comment by fhwebcs** [comment]
Hi, I'm trying to run this on my Intel NUC 10th gen (NUC10i5FNH). It works neither with a display nor with a HDMI Dummy Plug[1]. No kernel panics, but nothing on screen is visible (screen switch black immediately, then goes to standby).

[nuc10-hdmi-plug-serial.log](https://github.com/patmagauran/i915ovmfPkg/files/5745231/nuc10-hdmi-plug-serial.log) (generated by running ./test-gvt-d.sh; with bus=pci.0,addr=0x2 as well)

What host OS & Version: Ubuntu 20.04.1 LTS (Kernel 5.4.0-58-generic #64-Ubuntu)
SSH: Yes
QEMU Version: 4.2.1 (Debian 1:4.2-3ubuntu6.10)
Desktop / Laptop: Intel NUC
Displays connected: Yes (via HDMI-Port)
Other GPUS: No
Other system specs/info: i5-10210U CPU; iGPU-PCI: 8086:9b41 (UHD; Comet Lake)

[1]: HDMI Dummy Plug, Headless Ghost, Display Emulator (Fit Headless 1920x1080 New Generation @ 60Hz) (Brand: FUERAN; see on Amazon [here](https://www.amazon.de/-/en/Headless-Display-Emulator-1920x1080-Generation/dp/B06XT1Z9TF/)) 

Have a nice day. Let me know if you need any other details.

**Comment by my33love** [comment]
[gk41's ovmf](https://github.com/my33love/gk41-pve-ovmf)
try my file,maybe it will work!
(ubuntu vm work perfect!)

**Comment by fhwebcs** [comment]
@my33love Thank you. Looks promising. That is for UHD 600  (also 14nm, but Gen9)? Before I try, is it possible to build it by myself? What is included? As far as I can see on your github page, it's based on Project ACRN, right?

**Comment by my33love** [comment]
@fhwebcs  Replace Gop&VBT with UEFItool is too easy! no test ,you can try.
[NUC10i5FNH](https://github.com/my33love/gk41-pve-ovmf/tree/main/test)

**Comment by Kethen** [comment]
@fhwebcs 

With the hints from @my33love, I managed to build edk2 edk2-stable202105 with intel gop drivers extracted from my laptop's bios (kabylake), and bits from https://github.com/projectacrn/acrn-edk2

https://github.com/Kethen/edk2#readme might be helpful

Vbt.bin and IntelGopDriver.efi can be extracted from your bios using https://github.com/LongSoft/UEFITool

IntelGopDriver.efi:

![image](https://user-images.githubusercontent.com/22017945/127104602-477dec76-0081-4b30-82b8-3d7e48196a48.png)

Vbt.bin

![image](https://user-images.githubusercontent.com/22017945/127104651-6466ab8d-adc6-4856-b1a7-90cb4cf96273.png)
