### ISSUE TITLE
Unable to passthrough iGPU (GVT-d)

### ISSUE THREAD

**Issue by rodriguezst** [patmagauran/i915ovmfPkg#14]
### Description
I was facing kernel panics when trying to boot OSX with the rom in release v0.2.1. I have tested with the latest zip you uploaded at Issue #10 and the kernel panic is gone but I still get some errors. I have opened a new issue because I don't know if it is the same as #10.

### System Info

- Host OS(Distro/Version): Debian 10 with backport kernel 5.9
- CPU: i3 8109u
- Any other GPUs: No
- Guest OS: OSX (scripts based on kholia's OSX-KVM repo)
- GVT-G or GVT-D: GVT-D
- Display connections: Dummy HDMI dongle connected to HDMI port but detected by Linux as a DP-1 port
- i915ovmfPkg Release version or Commit: v0.2.1 and zips at #10

### Qemu command
>qemu-system-x86_64 -enable-kvm -m $RAM_SIZE -cpu Penryn,kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,$MY_OPTIONS,+kvm_pv_unhalt,+kvm_pv_eoi \
          -vga none \
          -nographic \
          -machine q35 \
          -smp 4,cores=4 \
          -device vfio-pci,host=$PCILOC,romfile=./gvt/issue10/i915ovmf.rom,bus=pcie.0,addr=0x2 \
          -fw_cfg name=etc/igd-opregion,file=./gvt/opregion.bin \
          -fw_cfg name=etc/igd-bdsm-size,file=./gvt/bdsmSize.bin \
          -usb \
          -device usb-ehci,id=ehci \
          -device usb-kbd,bus=ehci.0 \
          -device usb-mouse,bus=ehci.0 \
          -device nec-usb-xhci,id=xhci \
          -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc" \
          -drive if=pflash,format=raw,readonly,file=./OVMF_CODE.fd \
          -drive if=pflash,format=raw,file=./OVMF_VARS-1024x768.fd \
          -smbios type=2 \
          -device ich9-ahci,id=sata \
          -drive id=OpenCoreBoot,if=none,snapshot=on,format=qcow2,file=OpenCore.qcow2 \
          -device ide-hd,bus=sata.2,drive=OpenCoreBoot \
          -drive id=MacHDD,if=none,snapshot=on,file=./macos_hd.qcow2,format=qcow2 \
          -device ide-hd,bus=sata.4,drive=MacHDD \
          -netdev tap,id=hostnet0,fd=3 3<>/dev/tap$TAP_IFINDEX \
          -device vmxnet3,netdev=hostnet0,id=net0,mac=$TAP_MAC \
          -d out_asm -d guest_errors -D debugLog.log

### Logs

**Full Log of VM**

> Driver starts!
i915: found device 8086-3EA5 0
i915: start
i915: set pci attrs
i915: made gop path
i915: installed child handle
i915: before QEMU shenanigans
BdsmSize=8388608
i915: vbt: 0x7FBFB400, bdb: 0x7FBFB430, sig: $B KLK    d0▒▒0, bsig: BO_AABOK▒t▒
i915: finding section 2
i915: Boot display type: 0x0000
i915: Child device size: 39
i915: Child device count: 8
i915: SetupOpRegion: OpRegion @ 0x7FBFB000 size 0x2000 in 2 pages
SetupStolenMemory: : stolen memory @ 0x7DF00000 size 0x800000
i915: SetupFwcfgStuff returns 0
i915: after QEMU shenanigans
Port A VBT info: CRT:0 DVI:0 HDMI:0 DP:0 eDP:0 USB-Type-C:0 TBT:0 type:0000
VBT HDMI level shift for port A: 0
VBT DP max link rate for port A: 810000
Port B VBT info: CRT:0 DVI:1 HDMI:1 DP:1 eDP:0 USB-Type-C:0 TBT:0 type:60D6
VBT HDMI level shift for port B: 8
VBT DP max link rate for port B: 810000
Port C VBT info: CRT:0 DVI:1 HDMI:1 DP:1 eDP:0 USB-Type-C:0 TBT:0 type:60D6
VBT HDMI level shift for port C: 8
VBT DP max link rate for port C: 810000
More than one child device for port A in VBT, using the first.
Port E VBT info: CRT:0 DVI:0 HDMI:0 DP:0 eDP:0 USB-Type-C:0 TBT:0 type:0000
VBT HDMI level shift for port E: 0
VBT DP max link rate for port E: 810000
More than one child device for port A in VBT, using the first.
More than one child device for port A in VBT, using the first.
More than one child device for port A in VBT, using the first.
i915: power well enabled F00003FF
panel power sequencer register settings: PP_ON #x, PP_OFF #x, PP_DIV #x
PP_CTL:  00000000, PP_STAT  00000000
PP_CTL:  00000043, PP_STAT  9000000A
PP_CTL:  00000043, PP_STAT  80000008
i915: CDCLK = 080002A1
i915: DBUF timeout
i915: _PLANE_BUF_CFG_1_A = 00000000
i915: _PLANE_BUF_CFG_1_A = 035B0000 (after)
i915: SFUSE_STRAP = 00000106
Port A VBT info: DVI:0 HDMI:0 DP:0 eDP:0
i915: Port Is Connected!
Port B VBT info: DVI:1 HDMI:1 DP:1 eDP:0
i915: Port Is Connected!
using AUX B for port B (VBT)
i915: Port is DP/EdP. Aux_ch is 1
i915: trying DP aux 1
i915: reading DP aux 1
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
i915: ReadEDIDDP returned 14
i915: Port is HDMI. GMBUS Pin is 1
i915: trying pin 1
i915: gmbus error on 2048
i915: trying pin 1
i915: gmbus error on 2048
i915: trying pin 1
i915: gmbus error on 2048
i915: trying pin 1
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
i915: ReadEDIDHDMI returned 14
Port C VBT info: DVI:1 HDMI:1 DP:1 eDP:0
i915: Port Is Connected!
using AUX C for port C (VBT)
i915: Port is DP/EdP. Aux_ch is 2
i915: trying DP aux 2
i915: ReadEDIDDP returned 14
i915: Port is HDMI. GMBUS Pin is 2
i915: trying pin 2
i915: gmbus error on 2048
i915: ReadEDIDHDMI returned 14
Port A VBT info: DVI:0 HDMI:0 DP:0 eDP:0
i915: Port Is Connected!
Port E VBT info: DVI:0 HDMI:0 DP:0 eDP:0
i915: Port not connected
Port A VBT info: DVI:0 HDMI:0 DP:0 eDP:0
i915: Port Is Connected!
Port A VBT info: DVI:0 HDMI:0 DP:0 eDP:0
i915: Port Is Connected!
Port A VBT info: DVI:0 HDMI:0 DP:0 eDP:0
i915: Port Is Connected!
i915: failed to Set OutputPath
i915: DisplayInit Error. 14

>UEFI Interactive Shell v2.2
EDK II
UEFI v2.70 (EDK II, 0x00010000)
Mapping table
      FS0: Alias(s):HD0c65535a1:;BLK1:
          PciRoot(0x0)/Pci(0x4,0x0)/Sata(0x2,0xFFFF,0x0)/HD(1,GPT,F672C811-C98F-4955-9B6A-4AAAD0A7A95A,0x800,0x48BE1)
      FS1: Alias(s):HD0c65535a2:;BLK2:
          PciRoot(0x0)/Pci(0x4,0x0)/Sata(0x2,0xFFFF,0x0)/HD(2,GPT,BA339653-FA6D-4CBE-A3E9-213C36738F37,0x49BE0,0x75C21)
      FS2: Alias(s):HD0e65535a1:;BLK4:
          PciRoot(0x0)/Pci(0x4,0x0)/Sata(0x4,0xFFFF,0x0)/HD(1,GPT,431B2934-09D1-4264-9E9C-3F94E3F83361,0x28,0x64000)
     BLK0: Alias(s):
          PciRoot(0x0)/Pci(0x4,0x0)/Sata(0x2,0xFFFF,0x0)
     BLK3: Alias(s):
          PciRoot(0x0)/Pci(0x4,0x0)/Sata(0x4,0xFFFF,0x0)
     BLK5: Alias(s):
          PciRoot(0x0)/Pci(0x4,0x0)/Sata(0x4,0xFFFF,0x0)/HD(2,GPT,CDC1413C-FE0E-4991-BFC7-C5E22E9C9B92,0x64028,0x7F9BFB0)

>Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
Shell> fs0:\EFI\BOOT\BOOTx64.efi
BS: Starting OpenCore...
BS: Booter path - \EFI\BOOT\BOOTx64.efi
OCFS: Trying to locate filesystem on 7EE2A718 7EB1EF98
OCFS: Filesystem DP is \EFI\BOOT\BOOTx64.efi
BS: Trying to start loaded OpenCore image...
BS: Failed to locate bootstrap protocol - Not Found
BS: Trying to load OpenCore image...
BS: Read OpenCore image of 767744 bytes
BS: Loaded OpenCore image at 7EB1E898 handle
OC: Starting OpenCore...
OC: Booter path - <nil>
OC: Booted from bootstrap
OC: ReRun executed!
OCST: Missing vault data, ignoring...
OC: OcMiscEarlyInit...
OC: Loaded configuration of 21462 bytes
OCS: Missing key Arch, context <Add>!
OCS: Missing key Arch, context <Add>!
OCS: Missing key DummyPowerManagement, context <Emulate>!
OCS: Missing key MaxKernel, context <Emulate>!
OCS: Missing key MinKernel, context <Emulate>!
OCS: Missing key Arch, context <Patch>!
OCS: Missing key Arch, context <Patch>!
OCS: No schema for DummyPowerManagement at 8 index, context <Quirks>!
OCS: Missing key ExtendBTFeatureFlags, context <Quirks>!
OCS: Missing key ForceSecureBootScheme, context <Quirks>!
OCS: Missing key LegacyCommpage, context <Quirks>!
OCS: Missing key ProcessorType, context <Generic>!
OCS: Missing key SystemMemoryStatus, context <Generic>!
OCS: Missing key CustomMemory, context <PlatformInfo>!
OCS: Missing key ForceResolution, context <Output>!
OCS: Missing key ReservedMemory, context <UEFI>!
OC: Watchdog status is 1
OCC: Missing compatible GOP - Not Found
OCC: Missing GOP on ConOut - Unsupported
OC: Changed resolution to 1920x1080@0 (max: 0, force: 0) from 1920x1080@32 - Unsupported
OCUI: Failed to initialise output
OCB: ShowMenu failed - Unsupported
Halting on critical error

**Anything in dmesg/syslog**
Nothing

**Anything else you have found**
I have a dummy hdmi dongle connected to HDMI port but detected by Linux as a DP-1 port:

>$  cat /sys/devices/pci0000\:00/0000\:00\:02.0/drm/card0/card0-DP-1/status
connected
$  cat /sys/devices/pci0000\:00/0000\:00\:02.0/drm/card0/card0-DP-2/status
disconnected
$  cat /sys/devices/pci0000\:00/0000\:00\:02.0/drm/card0/card0-HDMI-A-1/status
disconnected

**Comment by midi1996** [comment]
as far as I can tell, your OC setup is broken and OC couldn't load, your iGPU might actually be fully passed.

**Comment by WesBosch** [comment]
Oh hey @midi1996 funny seeing you here.

Incidentally I'm facing the exact same issues as above even without using the rom from this repo, so I suspect you may be right about OC being the issue here, but I'm uncertain as to what could be broken. (It works fine without gvt-passthrough) perhaps the version of opencore we're using isn't compatible for some reason?

**Comment by patmagauran** [comment]
I do not know how dummy connectors work, but that may be part of the issue. The ROM is setup to passthrough the whole GPU and therefore expects a display. You may have luck by going through the code to incorporate a fallback EDID. However, OpenCore also requires a display out, so if you are going for a headless setup you would have to specifically look into how that works as I do not know,
