### ISSUE TITLE
What about Gen 11 integrated graphics (Intel Iris XE)?

### ISSUE THREAD

**Issue by Zeltinger** [patmagauran/i915ovmfPkg#15]
Is it supposed to work?

**Comment by patmagauran** [comment]
It is officially unsupported. You are welcome to test it, but from a cursory overlook, there were likely many changes that would reduce compatibility. I do not have any test hardware so I will not be pursuing it. If you wish to: The intel PRMs are a great starting point: https://01.org/linuxgraphics/documentation/hardware-specification-prms. You could also look through the changes to the intel i915 drivers in the linux kernel to support intel Iris XE as most of this code is based off of that code.
