### ISSUE TITLE
Macos config

### ISSUE THREAD

**Issue by Silfalion** [patmagauran/i915ovmfPkg#19]
Hi, if it's not too much asked, is it possible for you to share your OSX-KVM EFI please? without the serial number parts of course.

**Comment by midi1996** [comment]
I think you should make your own.

**Comment by Silfalion** [comment]
Why is that?

**Comment by patmagauran** [comment]
In the midst of moving files around, I do not have access to it anymore. As far as I remember, there weren't too many changes needed outside of the normal OSX-KVM ones.

**Comment by Silfalion** [comment]
Thank you and sorry for the delay, will give it a try later on.
