### ISSUE TITLE
Compiling Is not working

### ISSUE THREAD

**Issue by xXTeraXx** [patmagauran/i915ovmfPkg#20]
I have been trying to do this for the last 4 hours.   I followed the guide on the wiki page.  The first problem was that there was a typo.  It has to be mkdir i915-dev not i195-dev.  That was a easy fix.  Unfortunately no matter what I do I can't get this error to go away.  Even though the file is sitting right in the folder where it has to be.

/home/USER/i915dev/i915ovmfPkg/i915ovmf.dsc(133): error 000E: File/directory not found in workspace
	OvmfPkg/Library/BaseMemEncryptSevLib/BaseMemEncryptSevLib.inf is not found in packages path:
	/home/USER/i915dev/edk2
	/home/USER/i915dev/edk2-platforms

Output of ls in i915ovmfPkg
Notes			i915_controller.h  i915_hdmi.h	     mmio
QemuFwCfgLib.c		i915_ddi.c	   i915_reg.h	     shutdown.c
QemuFwCfgLib.h		i915_ddi.h	   i915ovmf.c	     shutdown.efi
QemuFwCfgLibInternal.h	i915_display.c	   i915ovmf.dec      t
QemuFwCfgPei.c		i915_display.h	   **i915ovmf.dsc**      target.txt
README.md		i915_dp.c	   i915ovmf.h	     test
Release			i915_dp.h	   i915ovmf.inf      test-gvt-d.sh
bdsmSize.bin		i915_gmbus.c	   intel_opregion.c  unbind.sh
bind.sh			i915_gmbus.h	   intel_opregion.h  vm.xml
bindtoi915		i915_gop.c	   intel_vbt.c
build.sh		i915_gop.h	   intel_vbt.h
clean.sh		i915_hdmi.c	   iommu.sh

**Comment by xXTeraXx** [comment]
Oh I forgot to say that I need to custom compile it for mac os.  I made some modifications to the files (i915_display.c) but I also tried it without the modifications

**Comment by xXTeraXx** [comment]
Update: Its still not working but I did get this build.py...
 : error 2000: Invalid parameter
	Invalid ARCH specified. [Valid ARCH: X64]

**Comment by Itay1787** [comment]
Same. I tried to do build in Debian failed exactly the same way.

**Comment by xXTeraXx** [comment]
I honestly think that the dev has not updated this in a while.  EDK2/Tianocore has gone through at least 50-100 commits in the time span between when the last commit to this project has been done and now.  Also btw I was on arch trying to do this though I do not think it makes a difference

**Comment by Itay1787** [comment]
Bummer!
It was my only hope to get something on screen from my IGPU on MacOS or Windows

**Comment by xXTeraXx** [comment]
I can get a screen with mac os and windows.  For windows make sure that DMA-BUF is on.  And for mac os it does work but it is stuck at 720p.  Also for windows you need to be using legacy mode for QEMU that use DMA-BUF there is a guide on the arch wiki.  Although if you are using the GTK view instead of remoting in your VM will be locked to 30 hertz

**Comment by xXTeraXx** [comment]
If I really start to get outraged soon, I might just fork the entire project and try to keep in maintained, but that project will be for another day.

**Comment by Itay1787** [comment]
>  For windows make sure that DMA-BUF is on. 
 Also for windows you need to be using legacy mode

Hi, I'm using Proxmox do you know how I make sure DMA-BUF is enabled? And do I really have to have my VM on legacy mode? It will not work if it is on UEFI?
Thanks

**Comment by xXTeraXx** [comment]
For proxmox, DMA-BUF does not work because of proxmox's remote access. For windows guests, you can actually use GVT-G In UEFI you just need a different rom file.  It used to be in the Arch wiki but that link has long since gone dead.  I happen to have it so I will post a link for it.  This rom file unfortunately does not let the GPU use the BIOS/UEFI screen (This also happens in legacy mode) so the GPU will only start working AFTER the driver is loaded in either windows or Linux.  Keep in mind that on windows guests, EDP (integrated laptop screens) will not work.  For proxmox you also need some extra arguments.  First, make sure that your VM is set to SeaBios and Q35 or OVMF and Q35 (See Below) then paste this into your VM config file. (/etc/pve/qemu-server/VMID.conf) at the top

Seabios:
args: " -device vfio-pci,sysfsdev=INSERT GVT ID,x-igd-opregion=on,addr=0x18,driver=vfio-pci-nohotplug"  

OVMF:
args: " -device vfio-pci,sysfsdev=INSERT GVT ID,x-igd-opregion=on,addr=0x18,driver=vfio-pci-nohotplug,romfile="  

Then you can boot back up your windows VM which should still have the default vga adapter.  Then start up the VM and install the intel drivers for windows.  You can either wait for windows to install the intel driver by itself or install the driver from the intel website.  For me personally the intel driver via the website will always fail if the default adapter is still present.  So I just wait for windows to install its driver (check windows update).  Most of the time that also says that it failed by it actually didn't.  So even if the win update driver fails, just shutdown the VM anways.  After that remove the default display adapter and start back up your VM and wait for it to finish booting.  After that try to RDP into the machine and Volia its working with no errors.

ROM File for OVMF (Place into /usr/share/kvm) 
https://www.mediafire.com/file/7a032jgqvallecm/vbios_gvt_uefi.rom/file
This rom file will use the full res of your display.

Original Link to Arch Wiki
https://wiki.archlinux.org/index.php/Intel_GVT-g#Using_DMA-BUF_with_UEFI/OVMF

**Comment by Itay1787** [comment]
> For proxmox, DMA-BUF does not work because of proxmox's remote access. For windows guests, you can actually use GVT-G In UEFI you just need a different rom file. It used to be in the Arch wiki but that link has long since gone dead. I happen to have it so I will post a link for it. This rom file unfortunately does not let the GPU use the BIOS/UEFI screen (This also happens in legacy mode) so the GPU will only start working AFTER the driver is loaded in either windows or Linux. Keep in mind that on windows guests, EDP (integrated laptop screens) will not work. For proxmox you also need some extra arguments. First, make sure that your VM is set to SeaBios and Q35 or OVMF and Q35 (See Below) then paste this into your VM config file. (/etc/pve/qemu-server/VMID.conf) at the top
> 
> Seabios:
> args: " -device vfio-pci,sysfsdev=INSERT GVT ID,x-igd-opregion=on,addr=0x18,driver=vfio-pci-nohotplug"
> 
> OVMF:
> args: " -device vfio-pci,sysfsdev=INSERT GVT ID,x-igd-opregion=on,addr=0x18,driver=vfio-pci-nohotplug,romfile=vbios_gvt_uefi.rom"
> 
> Then you can boot back up your windows VM which should still have the default vga adapter. Then start up the VM and install the intel drivers for windows. You can either wait for windows to install the intel driver by itself or install the driver from the intel website. For me personally the intel driver via the website will always fail if the default adapter is still present. So I just wait for windows to install its driver (check windows update). Most of the time that also says that it failed by it actually didn't. So even if the win update driver fails, just shutdown the VM anways. After that remove the default display adapter and start back up your VM and wait for it to finish booting. After that try to RDP into the machine and Volia its working with no errors.
> 
> ROM File for OVMF (Place into /usr/share/kvm)
> https://www.mediafire.com/file/7a032jgqvallecm/vbios_gvt_uefi.rom/file
> This rom file will use the full res of your display.
> 
> Original Link to Arch Wiki
> https://wiki.archlinux.org/index.php/Intel_GVT-g#Using_DMA-BUF_with_UEFI/OVMF

Thank you very much, for the ROM and the detailed explanation!
Just a little question when you mean `INSERT GVT ID` what am I putting there? `00:02.0` or `8086:5912` ?

**Comment by xXTeraXx** [comment]
uhh you had to make a gvt id.  Assuming that you already have GVT setup correctly all you have to do is 

`echo 72bd2118-0603-42a4-944c-78956d5e2290 >/sys/devices/pci0000\:00/0000\:00\:02.0/mdev_supported_types/i915-GVTg_V5_4/create/`.  

The  72bd2118-0603-42a4-944c-78956d5e2290 is the GVT ID.  Than you have to run that command on start by either making a systemd service, or adding it to /etc/rc.local and do chmod 755 /etc/rc.local or just run the command on start every time.  Just a quick thing.  I would recommend using WHOLE IGPU passthrough if your hardware supports it.  You can do this removing the gvt line from the command and adding the passthrough.  Unfortunately my hardware does not support this properly.

lines to add for WHOLE igpu passthrough 
OVMF
args: "-device vfio-pci,host=00:02.0,addr=0x18,x-igd-opregion=on,romfile=vbios_gvt_uefi.rom"

Seabios
args: "-device vfio-pci,host=00:02.0,addr=0x18,x-igd-opregion=on"

**Comment by Itay1787** [comment]
I think my hardware supports whole IGPU passthrough
Because in linux it seems to work (I did not check it too deeply)
And I also really prefer to do passthrough for the whole IGPU.
If I want to do passthrough for the whole IGPU I still need that GVT and the GVT ID? And run the command:
> echo 72bd2118-0603-42a4-944c-78956d5e2290 >/sys/devices/pci0000\:00/0000\:00\:02.0/mdev_supported_types/i915-GVTg_V5_4/create/ 

?
Or just add this line

> OVMF
> args: "-device vfio-pci,host=00:02.0,addr=0x18,x-igd-opregion=on,romfile=vbios_gvt_uefi.rom"

 to VM Config?
I still do not quite understand how exactly the passthrough at Intel works ...

**Comment by Itay1787** [comment]
> uhh you had to make a gvt id. Assuming that you already have GVT setup correctly all you have to do is
> 
> `echo 72bd2118-0603-42a4-944c-78956d5e2290 >/sys/devices/pci0000\:00/0000\:00\:02.0/mdev_supported_types/i915-GVTg_V5_4/create/`.
> 
> The 72bd2118-0603-42a4-944c-78956d5e2290 is the GVT ID. Than you have to run that command on start by either making a systemd service, or adding it to /etc/rc.local and do chmod 755 /etc/rc.local or just run the command on start every time. Just a quick thing. I would recommend using WHOLE IGPU passthrough if your hardware supports it. You can do this removing the gvt line from the command and adding the passthrough. Unfortunately my hardware does not support this properly.
> 
> lines to add for WHOLE igpu passthrough
> OVMF
> args: "-device vfio-pci,host=00:02.0,addr=0x18,x-igd-opregion=on,romfile=vbios_gvt_uefi.rom"
> 
> Seabios
> args: "-device vfio-pci,host=00:02.0,addr=0x18,x-igd-opregion=on"


So I was able to turn on the GVT-g in my Proxmox. And after I add the line you gave me to the VM file I get this error:` kvm: -device vfio-pci,sysfsdev=72bd2118-0603-42a4-944c-78956d5e2290,x-igd-opregion=on,addr=0x18,driver=vfio-pci-nohotplug,romfile=vbios_gvt_uefi.rom: vfio 72bd2118-0603-42a4-944c-78956d5e2290: no such host device: No such file or directory`
 
And if I put this line: `args: -device vfio-pci,host=00:02.0,addr=0x18,x-igd-opregion=on,romfile=vbios_gvt_uefi.rom `in the VM file I get this error:`kvm: -device vfio-pci,host=00:02.0,addr=0x18,x-igd-opregion=on,romfile=vbios_gvt_uefi.rom: vfio 0000:00:02.0: does not support requested IGD OpRegion feature: No such device`

What is left to do? Is there more hope?
Thanks so much for all the help!

**Comment by xXTeraXx** [comment]
Sorry for the late reply.   Please send me your hardware specs so I can see what GPU/IGPU you have.  If its a laptop just say the CPU.  If its easier my discord username is TeraBot452:3335

**Comment by Itay1787** [comment]
> Sorry for the late reply. Please send me your hardware specs so I can see what GPU/IGPU you have. If its a laptop just say the CPU. If its easier my discord username is TeraBot452#3335

I sent you a friend request in discord
:)

**Comment by retracee** [comment]
I'm getting the same issue

**Comment by jmlingeman** [comment]
Same. I even tried checking a version of edk2 and edk2-platforms from Nov 2020 and the ARCH is invalid (only available is X64). 

It seems like I need to have edk2 installed to use the pre-compiled ROM file as I need to generate the OVMF file, correct?

**Comment by retracee** [comment]
> Same. I even tried checking a version of edk2 and edk2-platforms from Nov 2020 and the ARCH is invalid (only available is X64). 
> 
> It seems like I need to have edk2 installed to use the pre-compiled ROM file as I need to generate the OVMF file, correct? 

You could try this:
https://github.com/HouQiming/i915ovmfPkg

**Comment by Itay1787** [comment]
> Sorry for the late reply. Please send me your hardware specs so I can see what GPU/IGPU you have. If its a laptop just say the CPU. If its easier my discord username is TeraBot452#3335

My Hardware: 
Motherboard: GA-Z270-ultra gaming. 
CPU: i5 7600K 
iGPU: HD 630

**Comment by lion328** [comment]
I can compile it on Debian. I used edk2-stable202005 and edk2-platform from master.

**Comment by patmagauran** [comment]
Sorry for being inactive with this Repo. While I am away at school, it is much harder to do any development with it. You are welcome to fork it if you so desire. 

I don't know why it would complain about the Target Arch. In the Conf Folder for the EDKII Build system should be a file named `target.txt` It should have a TARGET_ARCH option which should be equal to X64. I also do not know what would need to change to compile on MacOS as I have not attempted to do so. 

Since I have not attempted to compile this in a while, refer to these instructions on getting EDKII setup: https://github.com/tianocore/tianocore.github.io/wiki/Getting-Started-with-EDK-II. If the latest release does not work, use one from November to December of 2020. 

If you are Still getting the errors(Especially for the debian compile), could you possible upload a zip file of the development directory?

There is a pre-compiled ROM in the releases of this Repo that should work. HouQiming's repo only works with GVT-G and I am not sure about full compatibility within that.

**Comment by patmagauran** [comment]
Reading the EDKII instructions, it mentions specifically building the BaseTools: https://github.com/tianocore/tianocore.github.io/wiki/Common-instructions#compile-build-tools

**Comment by saieno** [comment]
Hello patmagauran,

Thanks for responding at least! I will say, using the provided .rom file currently crashes my computer (and others I'm sure). Locks up and crashes. I'm on Linux Mint 20 currently, Intel Corporation UHD Graphics 630. I have everything setup as it should be for full iGPU passthru but the rom crashes my PC hard when used.

**Comment by saieno** [comment]
I suppose I should mention I have a i9900K Coffee Lake CPU

**Comment by patmagauran** [comment]
Interesting. There are many possible reasons for it to crash and catching the debug output can be very tricky. I would appreciate if you created a separate issue for that. Hopefully we can figure out the compiling problems though

**Comment by yumorimoto** [comment]
With regards to the build issue, it is definitely due to changes in more recent edk2.  My advice is to switch to the 202011 stable release branch to use the code as-is.

For example, `MemEncryptSevLib|OvmfPkg/Library/BaseMemEncryptSevLib/BaseMemEncryptSevLib.inf` was split up to separate versions like `DxeMemEncryptSevLib.inf `

So in another words;
after `$ git clone https://github.com/tianocore/edk2.git`
and `$ cd edk2`
**add:** `$ git switch stable/202011`
then update submodules: `$ git submodule update --init`

Might be worth updating the instructions on the wiki: https://github.com/patmagauran/i915ovmfPkg/wiki/Compiling

**Comment by xXTeraXx** [comment]
SUCESS!!!.  I'm sorry I have been inactive for so long and thanks  patmagauran for coming back to help.  Unfortunatly I am facing more problems with even getting full iGPU passthrough to work at all on my i9 10900, I patched the kernel with a FLR patch but unfortunately mac os windows and Linux refuse to boot.

**Comment by patmagauran** [comment]
I just successfully built using a clean install of Ubuntu 20.04.2 LTS. I have added appropriate instructions here: https://github.com/patmagauran/i915ovmfPkg/wiki/Compiling. Also I updated the [build.sh](https://github.com/patmagauran/i915ovmfPkg/blob/master/build.sh) script to do BaseTools Compiling.

**Comment by xXTeraXx** [comment]
Thanks I also got it to work so I think that it is finally time to close this issue, Thanks for all the help
