### ISSUE TITLE
Guest can't reboot !!!

### ISSUE THREAD

**Issue by unintialized** [patmagauran/i915ovmfPkg#23]
### Description

Testing with test-gvt-d.sh shows that the output is working, but it does not exit properly. The system freezes, and pressing reset does not respond. Can only force power off.

### System Info

- Host OS(Distro/Version)
linux 5.10.52-rt47  SMP PREEMPT_RT

- CPU
intel i5 10400

- Any other GPUs
none

- Guest OS
windows10 LTSC

- GVT-G or GVT-D
GVT-D

- Display connections
HDMI

- i915ovmfPkg Release version or Commit
v0.2.1

### Qemu command
timeout --foreground -k 1 8 sudo qemu-system-x86_64 -k en-us -name uefitest,debug-threads=on -nographic -vga none -chardev stdio,id=char0,logfile=serial.log,signal=off   -serial chardev:char0 -m 2048 -M pc -cpu host -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -machine kernel_irqchip=on -nodefaults -rtc base=localtime,driftfix=slew -no-hpet -global kvm-pit.lost_tick_policy=discard -enable-kvm -bios /home/**/i915ovmfPkg/OVMF_CODE.fd -device vfio-pci,host=0000:00:02.0,romfile=`pwd`/i915ovmf.rom -device qemu-xhci,p2=8,p3=8 -device usb-kbd -device usb-tablet -drive format=raw,file=disk -usb

*If you used one of the included scripts, just note that*
test-gvt-d.sh

### Logs

$  sudo qemu-system-x86_64 -k en-us -name uefitest,debug-threads=on -nographic -vga none -chardev stdio,id=char0,logfile=serial.log,signal=off   -serial chardev:char0 -m 2048 -M pc -cpu host -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -machine kernel_irqchip=on -nodefaults -rtc base=localtime,driftfix=slew -no-hpet -global kvm-pit.lost_tick_policy=discard -enable-kvm -bios /home/**/i915ovmfPkg/OVMF_CODE.fd -device vfio-pci,host=0000:00:02.0,romfile=`pwd`/i915ovmf.rom -device qemu-xhci,p2=8,p3=8 -device usb-kbd -device usb-tablet -drive format=raw,file=disk -usb

Driver starts!
i915: found device 8086-9BC8 0
i915: start
i915: set pci attrs
i915: made gop path
i915: installed child handle
i915: before QEMU shenanigans
BdsmSize=8388608
i915: vbt: 0x7FBFB400, bdb: 0x7FBFB430, sig: $B KLK    d0▒▒0, bsig: BO_AABOK▒t▒
i915: finding section 2
i915: Boot display type: 0x0000
i915: Child device size: 39
i915: Child device count: 8
i915: SetupOpRegion: OpRegion @ 0x7FBFB000 size 0x2000 in 2 pages
SetupStolenMemory: : stolen memory @ 0x7E200000 size 0x800000
i915: SetupFwcfgStuff returns 0
i915: after QEMU shenanigans
Port A VBT info: CRT:0 DVI:0 HDMI:0 DP:0 eDP:0 USB-Type-C:0 TBT:0 type:0000
VBT HDMI level shift for port A: 0
VBT DP max link rate for port A: 810000
Port B VBT info: CRT:0 DVI:16 HDMI:1 DP:0 eDP:0 USB-Type-C:0 TBT:0 type:60D2
VBT HDMI level shift for port B: 10
VBT (e)DP boost level for port B: 1
VBT HDMI boost level for port B: 7
VBT DP max link rate for port B: 810000
Port C VBT info: CRT:0 DVI:16 HDMI:1 DP:0 eDP:0 USB-Type-C:0 TBT:0 type:60D2
VBT HDMI level shift for port C: 10
VBT DP max link rate for port C: 810000
Port D VBT info: CRT:0 DVI:16 HDMI:1 DP:4 eDP:0 USB-Type-C:0 TBT:0 type:60D6
VBT HDMI level shift for port D: 10
VBT DP max link rate for port D: 810000
More than one child device for port A in VBT, using the first.
More than one child device for port A in VBT, using the first.
More than one child device for port A in VBT, using the first.
More than one child device for port A in VBT, using the first.
i915: power well enabled F00002BB
panel power sequencer register settings: PP_ON #x, PP_OFF #x, PP_DIV #x
PP_CTL:  00000000, PP_STAT  00000000
PP_CTL:  00000003, PP_STAT  9000000A
PP_CTL:  00000003, PP_STAT  90000009
i915: CDCLK = 0C000544
i915: DBUF timeout
i915: _PLANE_BUF_CFG_1_A = 00000000
i915: _PLANE_BUF_CFG_1_A = 035B0000 (after)
i915: SFUSE_STRAP = 00000005
i915: trying pin 5
i915: trying pin 5
i915: gmbus timeout
i915: trying pin 5
00 FF FF FF FF FF FF 00
4C 2D 45 0B 42 47 5A 5A
14 1C 01 03 80 34 1D 78
2A 7D D1 A4 56 50 A1 28
0F 50 54 BF EF 80 71 4F
81 C0 81 00 81 80 95 00
A9 C0 B3 00 01 01 02 3A
80 18 71 38 2D 40 58 2C
45 00 09 25 21 00 00 1E
01 1D 00 72 51 D0 1E 20
6E 28 55 00 09 25 21 00
00 1E 00 00 00 FD 00 32
4B 1E 51 11 00 0A 20 20
20 20 20 20 00 00 00 FC
00 53 32 34 44 33 30 30
0A 20 20 20 20 20 01 7F
Mode: 148500, Max:300000
I915: HUsing Connector Mode: 0, On Port 1Reading PP_STATUS: 2415919113
i915: got EDID:
00 FF FF FF FF FF FF 00
4C 2D 45 0B 42 47 5A 5A
14 1C 01 03 80 34 1D 78
2A 7D D1 A4 56 50 A1 28
0F 50 54 BF EF 80 71 4F
81 C0 81 00 81 80 95 00
A9 C0 B3 00 01 01 02 3A
80 18 71 38 2D 40 58 2C
45 00 09 25 21 00 00 1E
01 1D 00 72 51 D0 1E 20
6E 28 55 00 09 25 21 00
00 1E 00 00 00 FD 00 32
4B 1E 51 11 00 0A 20 20
20 20 20 20 00 00 00 FC
00 53 32 34 44 33 30 30
0A 20 20 20 20 20 01 7F
i915: bar ranges - 810000000 1000000, 800000000 10000000
i915: aperture at 800000000
i915: gmadr = 00000000, size = 00000000, hgmadr = 00000000, hsize = 00000000
i915: 1920x1080 clock=148500
i915: ggtt_base at 810800000, entries: 00000000 00000000, backing fb: 7DA00000, 7F9E00 bytes
i915: progressed to mline 669, status is 0
i915: set mode 0
i915: DPLL_CTRL1 = 00000845
i915: _DPLL1_CFGCR1 = 80400173
i915: _DPLL1_CFGCR2 = 000003A5
i915: DPLL 1 locked
i915: port is 1
i915: DPLL_CTRL2 = 00A00018
i915: progressed to line 119, TRANS_CLK_SEL_PORT(port) is 40000000
i915: before TranscoderPipe  0
i915: HTOTAL_A (60000) = 0897077F
i915: HBLANK_A (60004) = 0897077F
i915: HSYNC_A (60008) = 080307D7
i915: VTOTAL_A (6000C) = 04640437
i915: VBLANK_A (60010) = 04640437
i915: VSYNC_A (60014) = 0440043B
i915: PIPEASRC (6001C) = 077F0437
i915: BCLRPAT_A (60020) = 00000000
i915: VSYNCSHIFT_A (60028) = 00000000
i915: PIPE_MULT_A (6002C) = 00000000
i915: before pipe gamma
i915: after TranscoderPipe
i915: before gamma
i915: before pipe gamma
REGISTER 70008
i915Display: current line: 168
i915Display: current line: 171
i915Display: current line: 174
i915: before DDI
DDI Port: 1
REG TransDDI: 00030000
i915: after DDI
i915: pipe enabled
DDI_BUF_CTL(port) = 00000080
SAVED BTIS 00000000
DDI_BUF_CTL(port) = 80000080
i915: progressed to line 618, status is0
i915: plane enabled, dspcntr: 84002000, FbBase: 800000000
i915: Reg PP_CONTROL(000C7204), val: 00000007
i915: Reg _BXT_BLC_PWM_FREQ1(000C8254), val: 00017700
i915: Reg _BXT_BLC_PWM_DUTY1(000C8258), val: 00000000
i915: Reg PP_STATUS(000C7200), val: 90000009
i915: Reg DP_TP_CTL(00064140), val: 00000000
i915: Reg _PIPEEDPCONF(0007F008), val: 00000000
i915: Reg _PIPEACONF(00070008), val: C0000000
i915: Reg _DSPAOFFSET(000701A4), val: 00000000
i915: Reg _DSPAPOS(0007018C), val: 00000000
i915: Reg _DSPASTRIDE(00070188), val: 00000078
i915: Reg _DSPASIZE(00070190), val: 0437077F
i915: Reg _DSPACNTR(00070180), val: 84002000
i915: Reg _DSPASURF(0007019C), val: 00000000
i915: Reg DDI_BUF_CTL(00064100), val: 80000000
i915: Reg _TRANS_DDI_FUNC_CTL_EDP(0006F400), val: 00030000
i915: Reg _TRANS_EDP_MSA_MISC(0006F410), val: 00000000
i915: Reg _SKL_BOTTOM_COLOR_A(00070034), val: 00000000
i915: Reg _GAMMA_MODE_A(0004A480), val: 00000000
i915: Reg _LGC_PALETTE_A(0004A000), val: 00000000
i915: Reg DISPIO_CR_TX_BMU_CR0(0006C00C), val: 00000800
i915: Reg PP_ON(000C7208), val: 041A01F4
i915: Reg PP_OFF(000C720C), val: 09C401F4
i915: Reg PP_DIVISOR(00061210), val: 00000003
i915: Reg DPLL_CTRL1(0006C058), val: 00000845
i915: Reg LCPLL2_CTL(00046014), val: 80000000
i915: Reg LCPLL1_CTL(00046010), val: C0000000
i915: Reg DPLL_CTRL2(0006C05C), val: 00A00018
i195: Controller: LR: 0, LC: 0, Port: 1, ContType: 0, DPLL: 1
i915: progressed to gopline 201, status is 0
i915: progressed to mline 672, status is 0
i915: gop ready
i915: query mode
i915: query mode
i915: query mode
i915: query mode

**Full Log of VM**(From the time you run the qemu command until it exits)

**Anything in dmesg/syslog**
[  104.381655] DMAR: DRHD: handling fault status reg 3
[  104.381658] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9bd00000 [fault reason 06] PTE Read access is not set
[  104.382080] DMAR: DRHD: handling fault status reg 3
[  104.382082] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9bd00000 [fault reason 06] PTE Read access is not set
[  104.382525] DMAR: DRHD: handling fault status reg 3
[  104.382527] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9bd11000 [fault reason 06] PTE Read access is not set
[  104.382963] DMAR: DRHD: handling fault status reg 3
[  105.048892] vfio-pci 0000:00:02.0: vfio_ecap_init: hiding ecap 0x1b@0x100
[  105.051451] vfio-pci 0000:00:02.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0x0000
[  105.051484] vfio-pci 0000:00:02.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0x0000
[  105.051515] vfio-pci 0000:00:02.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0x0000
[  105.051544] vfio-pci 0000:00:02.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0x0000
[  109.397294] dmar_fault: 7702 callbacks suppressed
[  109.397297] DMAR: DRHD: handling fault status reg 3
[  109.397298] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  109.413960] DMAR: DRHD: handling fault status reg 3
[  109.413962] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  109.430628] DMAR: DRHD: handling fault status reg 3
[  109.430630] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  109.447295] DMAR: DRHD: handling fault status reg 3
[  114.413968] dmar_fault: 1124 callbacks suppressed
[  114.413976] DMAR: DRHD: handling fault status reg 3
[  114.413980] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  114.430640] DMAR: DRHD: handling fault status reg 3
[  114.430646] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  114.447301] DMAR: DRHD: handling fault status reg 3
[  114.447307] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  114.463968] DMAR: DRHD: handling fault status reg 3
[  119.413967] dmar_fault: 890 callbacks suppressed
[  119.413975] DMAR: DRHD: handling fault status reg 3
[  119.413979] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  119.430633] DMAR: DRHD: handling fault status reg 3
[  119.430640] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  119.447269] DMAR: DRHD: handling fault status reg 3
[  119.447275] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  119.463967] DMAR: DRHD: handling fault status reg 3
[  124.430636] dmar_fault: 893 callbacks suppressed
[  124.430644] DMAR: DRHD: handling fault status reg 3
[  124.430648] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  124.447300] DMAR: DRHD: handling fault status reg 3
[  124.447307] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  124.463966] DMAR: DRHD: handling fault status reg 3
[  124.463973] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  124.480632] DMAR: DRHD: handling fault status reg 3
[  129.447298] dmar_fault: 893 callbacks suppressed
[  129.447307] DMAR: DRHD: handling fault status reg 3
[  129.447311] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  129.463965] DMAR: DRHD: handling fault status reg 3
[  129.463973] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  129.480631] DMAR: DRHD: handling fault status reg 3
[  129.480639] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  129.497294] DMAR: DRHD: handling fault status reg 3
[  134.447297] dmar_fault: 890 callbacks suppressed
[  134.447306] DMAR: DRHD: handling fault status reg 3
[  134.447310] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  134.463977] DMAR: DRHD: handling fault status reg 3
[  134.463985] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  134.480637] DMAR: DRHD: handling fault status reg 3
[  134.480644] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  134.497298] DMAR: DRHD: handling fault status reg 3
[  139.463966] dmar_fault: 893 callbacks suppressed
[  139.463975] DMAR: DRHD: handling fault status reg 3
[  139.463979] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  139.480631] DMAR: DRHD: handling fault status reg 3
[  139.480638] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  139.497297] DMAR: DRHD: handling fault status reg 3
[  139.497303] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  139.513963] DMAR: DRHD: handling fault status reg 3
[  144.480629] dmar_fault: 893 callbacks suppressed
[  144.480638] DMAR: DRHD: handling fault status reg 3
[  144.480641] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  144.497296] DMAR: DRHD: handling fault status reg 3
[  144.497303] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  144.513963] DMAR: DRHD: handling fault status reg 3
[  144.513969] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  144.530629] DMAR: DRHD: handling fault status reg 3
[  149.497296] dmar_fault: 893 callbacks suppressed
[  149.497305] DMAR: DRHD: handling fault status reg 3
[  149.497308] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  149.513962] DMAR: DRHD: handling fault status reg 3
[  149.513969] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  149.530628] DMAR: DRHD: handling fault status reg 3
[  149.530635] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  149.547293] DMAR: DRHD: handling fault status reg 3
[  154.513959] dmar_fault: 893 callbacks suppressed
[  154.513968] DMAR: DRHD: handling fault status reg 3
[  154.513972] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  154.530628] DMAR: DRHD: handling fault status reg 3
[  154.530635] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  154.547269] DMAR: DRHD: handling fault status reg 3
[  154.547279] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  154.563961] DMAR: DRHD: handling fault status reg 3
[  159.530623] dmar_fault: 893 callbacks suppressed
[  159.530631] DMAR: DRHD: handling fault status reg 3
[  159.530635] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  159.547294] DMAR: DRHD: handling fault status reg 3
[  159.547301] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  159.563960] DMAR: DRHD: handling fault status reg 3
[  159.563967] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  159.580627] DMAR: DRHD: handling fault status reg 3
[  164.547294] dmar_fault: 893 callbacks suppressed
[  164.547303] DMAR: DRHD: handling fault status reg 3
[  164.547307] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  164.563962] DMAR: DRHD: handling fault status reg 3
[  164.563969] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  164.580625] DMAR: DRHD: handling fault status reg 3
[  164.580633] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  164.597293] DMAR: DRHD: handling fault status reg 3
[  169.563959] dmar_fault: 893 callbacks suppressed
[  169.563968] DMAR: DRHD: handling fault status reg 3
[  169.563971] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  169.580627] DMAR: DRHD: handling fault status reg 3
[  169.580635] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  169.597292] DMAR: DRHD: handling fault status reg 3
[  169.597300] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  169.613959] DMAR: DRHD: handling fault status reg 3
[  174.580625] dmar_fault: 893 callbacks suppressed
[  174.580634] DMAR: DRHD: handling fault status reg 3
[  174.580637] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  174.597290] DMAR: DRHD: handling fault status reg 3
[  174.597298] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  174.613958] DMAR: DRHD: handling fault status reg 3
[  174.613965] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  174.630592] DMAR: DRHD: handling fault status reg 3
[  179.597290] dmar_fault: 893 callbacks suppressed
[  179.597299] DMAR: DRHD: handling fault status reg 3
[  179.597303] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  179.613955] DMAR: DRHD: handling fault status reg 3
[  179.613962] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  179.630623] DMAR: DRHD: handling fault status reg 3
[  179.630630] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  179.647291] DMAR: DRHD: handling fault status reg 3
[  184.613959] dmar_fault: 893 callbacks suppressed
[  184.613968] DMAR: DRHD: handling fault status reg 3
[  184.613972] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  184.630623] DMAR: DRHD: handling fault status reg 3
[  184.630630] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  184.647289] DMAR: DRHD: handling fault status reg 3
[  184.647297] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  184.663956] DMAR: DRHD: handling fault status reg 3
[  189.630622] dmar_fault: 893 callbacks suppressed
[  189.630632] DMAR: DRHD: handling fault status reg 3
[  189.630635] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  189.647289] DMAR: DRHD: handling fault status reg 3
[  189.647296] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  189.663954] DMAR: DRHD: handling fault status reg 3
[  189.663962] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  189.680620] DMAR: DRHD: handling fault status reg 3
[  194.647288] dmar_fault: 893 callbacks suppressed
[  194.647297] DMAR: DRHD: handling fault status reg 3
[  194.647301] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  194.663954] DMAR: DRHD: handling fault status reg 3
[  194.663961] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  194.680621] DMAR: DRHD: handling fault status reg 3
[  194.680629] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  194.697287] DMAR: DRHD: handling fault status reg 3
[  199.663954] dmar_fault: 893 callbacks suppressed
[  199.663963] DMAR: DRHD: handling fault status reg 3
[  199.663966] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  199.680621] DMAR: DRHD: handling fault status reg 3
[  199.680628] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  199.697287] DMAR: DRHD: handling fault status reg 3
[  199.697293] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  199.713954] DMAR: DRHD: handling fault status reg 3
[  204.680622] dmar_fault: 893 callbacks suppressed
[  204.680630] DMAR: DRHD: handling fault status reg 3
[  204.680634] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  204.697286] DMAR: DRHD: handling fault status reg 3
[  204.697294] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  204.713950] DMAR: DRHD: handling fault status reg 3
[  204.713957] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  204.730619] DMAR: DRHD: handling fault status reg 3
[  209.697284] dmar_fault: 893 callbacks suppressed
[  209.697295] DMAR: DRHD: handling fault status reg 3
[  209.697300] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  209.713950] DMAR: DRHD: handling fault status reg 3
[  209.713957] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  209.730617] DMAR: DRHD: handling fault status reg 3
[  209.730624] DMAR: [DMA Read] Request device [00:02.0] PASID ffffffff fault addr 9c000000 [fault reason 06] PTE Read access is not set
[  209.747282] DMAR: DRHD: handling fault status reg 3

[  498.270899] vfio-pci 0000:00:02.0: not ready 1023ms after FLR; waiting
[  499.326855] vfio-pci 0000:00:02.0: not ready 2047ms after FLR; waiting
[  501.534762] vfio-pci 0000:00:02.0: not ready 4095ms after FLR; waiting
[  505.886589] vfio-pci 0000:00:02.0: not ready 8191ms after FLR; waiting
[  514.334205] vfio-pci 0000:00:02.0: not ready 16383ms after FLR; waiting
[  566.122595] vfio-pci 0000:00:02.0: can't change power state from D0 to D3hot (config space inaccessible)

**Anything else you have found**

/$ lspci -vvv

00:02.0 VGA compatible controller: Intel Corporation Device 9bc8 (rev ff) (prog-if ff)
        DeviceName: Onboard - Video
        !!! Unknown header type 7f
        Kernel driver in use: vfio-pci
        Kernel modules: i915

**Comment by patmagauran** [comment]
Unfortunately, the graphics hardware can get very unhappy about the switching. I haven't found a solution, although usually it can at least exit the VM first.

**Comment by Heath123** [comment]
My host also hangs after switching, it’s my only issue with this. It would be amazing if it could be fixed

**Comment by alexsarmiento** [comment]
`[ 498.270899] vfio-pci 0000:00:02.0: not ready 1023ms after FLR; waiting`

I had this problem.  The system freezes after the guest shuts down or reboots. 
The only fix I could find was to recompile a patched kernel with this patch that deals with flr stuff:

```
--- a/drivers/pci/quirks.c      2021-12-17 11:20:39.254159019 -0500
+++ b/drivers/pci/quirks.c      2021-12-17 11:27:18.181390599 -0500
@@ -5327,6 +5327,7 @@
 DECLARE_PCI_FIXUP_EARLY(PCI_VENDOR_ID_AMD, 0x149c, quirk_no_flr);
 DECLARE_PCI_FIXUP_EARLY(PCI_VENDOR_ID_INTEL, 0x1502, quirk_no_flr);
 DECLARE_PCI_FIXUP_EARLY(PCI_VENDOR_ID_INTEL, 0x1503, quirk_no_flr);
+DECLARE_PCI_FIXUP_EARLY(PCI_VENDOR_ID_INTEL, 0x5912, quirk_no_flr);

 static void quirk_no_ext_tags(struct pci_dev *pdev)
 {
```

Notice the same problem happens to other AMD and Intel hardware. This patch specifically workarounds my HD 630 with ID 5912 and the "proxmox/pve-kernel" kernel which is based on the ubuntu-jammy kernel 5.15.

With this the system no longer freezes with the gvt-d and the hard-shutdowns which are deeply annoying are no longer necessary.

**Comment by patmagauran** [comment]
Do you have a source for that patch or did you create it yourself? I may consider adding it to the wiki.

**Comment by alexsarmiento** [comment]
> Do you have a source for that patch or did you create it yourself? I may consider adding it to the wiki.

I did it myself because as far I can tell nobody else did. But I took the idea from here https://forum.proxmox.com/threads/pci-passthrough-onboard-sound.66342/post-334836. 

I guess other problematic IDs can be added. It would be nice if this project could also provide some pre compiled kernels with the patch.

**Comment by patmagauran** [comment]
I am archiving this repository and no longer offer support as the owner. Please see the discord for support: https://discord.gg/bGNgmmYcWb
