### ISSUE TITLE
opregion.bin missing

### ISSUE THREAD

**Issue by amaroo2006** [patmagauran/i915ovmfPkg#24]
after compiling the rom i was able to get the bdsmsize.bin and i915ovmf.rom file, but i was never given an opregion.bin file. /sys/kernel/debug/dri/0/ has not i915_opregion file, and no other directory in debug/dri has it either. is there something i'm doing incorrectly? i'm running ubuntu 20.04 with kernel 5.14.0-051400-generic

**Comment by patmagauran** [comment]
If you are following these directions: https://github.com/patmagauran/i915ovmfPkg/wiki/Qemu-FwCFG-Workaround and the directory `/sys/kernel/debug/dri/0/` doesn't have the opregion file, I do not know exactly why.

**Comment by Heath123** [comment]
For me I had to un-blacklist the i915 driver and turn off the VFIO options, and then it was in `/sys/kernel/debug/dri/1/` instead of `/sys/kernel/debug/dri/0/`

**Comment by patmagauran** [comment]
That's great! I will try to add it to the wiki.
