### ISSUE TITLE
Shall I try on 11th gen?

### ISSUE THREAD

**Issue by way2me** [patmagauran/i915ovmfPkg#25]
I know there are discussions around Xe graphics getting lot of changes from it past iternation. I got some ray of hope after seeing lspci -k output.
```
00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
	Subsystem: Dell Device 0a36
	Kernel driver in use: i915
	Kernel modules: i915
```
Here driver in use is i915. So is it logical to try or I should give up the hope with this one.

### System Info

- Host OS(Distro/Version): Arch
- CPU: i7 1185g7
- Any other GPUs None
- Guest OS: macOS
- GVT-G or GVT-D: Any
- Display connections: How to know?
- i915ovmfPkg Release version or Commit

Thanks

**Comment by patmagauran** [comment]
It likely will not work. I haven't read through all the PRMs but I am sure there are enough changes to prevent it from working. While it is unlikely it will break anything, I cannot guarantee it. Something as small as a clock frequency change could lead to a bad signal being sent to the display which could break it if it has not internal protection. Or a change in register address which writes bad values to gpu registers.

I welcome attempts to get it working. I would first compare the steps here: https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-tgl-vol12-displayengine.pdf  with the ones Here: https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-skl-vol12-display.pdf
Then compare the associated registers.
Also look at the appropriate commits and changes to the i915 driver in the linux kernel to add support for tigerlake(and probably everything between tigerlake and skylake). I mostly kept the files with the same names, layouts and code structure, just changed it to work with EDKII and this repository.

**Comment by wnark** [comment]
> It likely will not work. I haven't read through all the PRMs but I am sure there are enough changes to prevent it from working. While it is unlikely it will break anything, I cannot guarantee it. Something as small as a clock frequency change could lead to a bad signal being sent to the display which could break it if it has not internal protection. Or a change in register address which writes bad values to gpu registers.
> 
> I welcome attempts to get it working. I would first compare the steps here: https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-tgl-vol12-displayengine.pdf with the ones Here: https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-skl-vol12-display.pdf Then compare the associated registers. Also look at the appropriate commits and changes to the i915 driver in the linux kernel to add support for tigerlake(and probably everything between tigerlake and skylake). I mostly kept the files with the same names, layouts and code structure, just changed it to work with EDKII and this repository.

Hello, I use Intel N5105 nuc11, using the wiki method, successfully started qemu, showing the uefi interface

![image](https://user-images.githubusercontent.com/24355466/163817800-0df79381-aac2-4d00-b0f8-9bea14085bbf.png)
But my monitor still has no output
The dmesg information is as follows：
![image](https://user-images.githubusercontent.com/24355466/163817904-e2b2c8ca-b4f4-41b8-a98a-94b29f8cef2e.png)

May I ask whether my machine can successfully implement gvt-d output from hdmi (as long as Windows is installed) or not?
I tried to use legacy mode to achieve Intel gpu pass-through before, but it seems that the 11th generation cpu does not support this mode
