### ISSUE TITLE
OC: Boot failed - Aborted OCB: StartImage failed - Aborted

### ISSUE THREAD

**Issue by tylermmoore** [patmagauran/i915ovmfPkg#31]
Hi All, I have been trying to get this to work but not having much luck.  When i run the boot.sh script this is what i get.  I am not quite sure what the issue is (besides that Fwcfg workaround) which im trying to figure out how to handle. It look slike it gets to the Opencore bootloader but then nothing.

Any thoughts?  

qemu-system-x86_64: -fw_cfg name=etc/igd-opregion,file=./i915ovmf/opregion.bin: warning: externally provided fw_cfg item names should be prefixed with "opt/"
qemu-system-x86_64: -fw_cfg name=etc/igd-bdsm-size,file=./i915ovmf/bdsmSize.bin: warning: externally provided fw_cfg item names should be prefixed with "opt/"
qemu-system-x86_64: -device vfio-pci,host=0000:00:02.0,id=hostdev0,bus=pcie.0,addr=0x2,romfile=./i915ovmf/i915ovmf.rom: IGD device 0000:00:02.0 cannot support legacy mode due to existing devices at address 1f.0
i915 Message: efi_main(938)Driver starts!
i915 Message: i915ControllerDriverSupported(843)found device 8086-1912 0
i915 Message: i915ControllerDriverStart(498)start
i915 Message: i915ControllerDriverStart(528)set pci attrs
i915 Message: i915ControllerDriverStart(559)made gop path
i915 Message: i915ControllerDriverStart(571)installed child handle
i915 Message: i915ControllerDriverStart(579)before QEMU shenanigans
i915 Message: SetupFwcfgStuff(441)SetupFwcfgStuff: etc/igd-opregion: zero size
i915 Message: i915ControllerDriverStart(593)SetupFwcfgStuff Error 24. Please see https://github.com/RotatingFans/i915ovmfPkg/wiki/Qemu-FwCFG-Workaround for more information

OCS: No schema for AudioOut at 2 index, context <Audio>!
OCS: No schema for MinimumVolume at 4 index, context <Audio>!
OCS: No schema for VolumeAmplifier at 8 index, context <Audio>!
OCC: Missing compatible GOP - Not Found
OCC: Missing GOP on ConOut - Unsupported
OC: Changed resolution to 1280x720@0 (max: 0, force: 0) from 1280x720@32 - Unsupported
OCUI: Failed to initialise output
OCB: External interface ShowMenu failure, fallback to builtin - Unsupported

OpenCore Boot Menu (REL-077-2022-01-10)

* 1. monterey
  2. Recovery 12.3.1 (dmg)
  3. UEFI Shell
  4. Reset NVRAM

 |Restart|  |Shutdown|

Choose the Operating System: Timeout

OC: Boot failed - Aborted
OCB: StartImage failed - Aborted

Iommu Groups Info
(IOMMU Group 1:
	00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 530 [8086:1912] (rev 06)
)

**Comment by patmagauran** [comment]
> i915 Message: i915ControllerDriverStart(593)SetupFwcfgStuff Error 24. Please see https://github.com/RotatingFans/i915ovmfPkg/wiki/Qemu-FwCFG-Workaround for more information

This is likely the issue causing the problem. Also I will not do any opencore support for this. I prefer tests be done with a linux guest as it provides the most debug information and is free of any proprietary issues.
