### ISSUE TITLE
Unable to setup laptop screen brightness

### ISSUE THREAD

**Issue by manu-romero-411** [patmagauran/i915ovmfPkg#32]
I built i915ovmf for my Intel HD Graphics 620 iGPU on an Asus laptop from 2017 (Intel Core i7-7500U CPU). My ROM produces proper video output to the laptop screen, with Windows being able to boot and work. However, I can't adjust brightness on the screen - it always is in the maximum level. Using the Intel HD Graphics control panel in Windows lets me change colour and contrast settings, but not brightness. Seems like the screen is not recognized as a "laptop" screen.

Is there any patch or something (maybe in i915ovmf or in a custom edk2 BIOS) that I could apply to make the VM detect properly the screen and be able to set brightness?

Thanks in advance.

**Comment by samuel-owoaanu** [comment]
> I built i915ovmf for my Intel HD Graphics 620 iGPU on an Asus laptop from 2017 (Intel Core i7-7500U CPU). My ROM produces proper video output to the laptop screen, with Windows being able to boot and work. However, I can't adjust brightness on the screen - it always is in the maximum level. Using the Intel HD Graphics control panel in Windows lets me change colour and contrast settings, but not brightness. Seems like the screen is not recognized as a "laptop" screen.
> 
> Is there any patch or something (maybe in i915ovmf or in a custom edk2 BIOS) that I could apply to make the VM detect properly the screen and be able to set brightness?
> 
> Thanks in advance.

hello there, I'm glad to see that it worked for your computer, I have been trying to make it work for me too but it's been abortive, please can you put me through how you did it. I also have Intel HD Graphics 620 iGPU on a Lenovo Laptop (Intel Core i5-7200U CPPU)

**Comment by manu-romero-411** [comment]
I compiled this a while ago, so I don't remember clearly, sorry for that. I followed the steps in the [wiki](https://github.com/patmagauran/i915ovmfPkg/wiki/), paying more attention at the workaround mentioned there. One important thing is not to use the precompiled build, as it won't work anywhere.

**Comment by samuel-owoaanu** [comment]
thank you so much for your prompt response, I have been able to compile i915ovmf.rom now, but I still don't know how to use it.
I tried adding it to the romfile path for the pci passthrough, but it didn't work, the laptop screen only went blank.
please I need help.

thanks a lot.

**Comment by HouQiming** [comment]
There are many information sources for detecting the presence of an
Intel-standard backlight. i915ovmfPkg only exposes the opregion one.
Windows seemed to require an ACPI backlight interface which I haven't been
able to reproduce correctly. You're welcome to try, but an ACPI table tweak
is more likely to work than any ROM code tweak.

**Comment by patmagauran** [comment]
I am archiving this repository and no longer offer support as the owner. Please see the discord for support: https://discord.gg/bGNgmmYcWb
