### ISSUE TITLE
can this be used on real machines without vt-x/vifo? thx

### ISSUE THREAD

**Issue by kocoman1** [patmagauran/i915ovmfPkg#34]
can this be used on real machines without vt-x/vifo? thx

**Comment by HouQiming** [comment]
Theoretically, yes. But it doesn't make much sense: Intel includes an
official display driver in their FSP (Firmware Support Package), which is
needed in the regular BIOS for other essential functionality anyway. After
FSP, the display is already initialized so this VBIOS becomes redundant.

I'm curious: why would you want to run it on real machines?

**Comment by kocoman1** [comment]
its for running osx. now it only works when i use vbios 16bit and not with libgfxibit in coreboot
