### ISSUE TITLE
Host machine hang after run test-gvt-d.sh

### ISSUE THREAD

**Issue by kimown** [patmagauran/i915ovmfPkg#41]
**FIRST** Have you tried with the included scripts? Can you do regular vfio passthrough? Is there a clearly printed error? 

Have you Looked at https://github.com/RotatingFans/i915ovmfPkg/wiki/Having-Problems%3F

Yes

### Description
 I am following [doc](https://github.com/patmagauran/i915ovmfPkg/wiki/Using) step by step, but my host machine hang after I run ` sudo ./test-gvt-d.sh` , I have to restart machine by long press power button.
### System Info

- Host OS(Distro/Version) : Ubuntu 22.04.3 LTS 6.2.0-32-generic
- CPU :   i7-10700K CPU 
- Any other GPUs  :  Nvidia 
- Guest OS: N/A
- GVT-G or GVT-D : GVT-D
- Display connections :  DP
- i915ovmfPkg Release version or Commit: https://github.com/patmagauran/i915ovmfPkg/releases/tag/V0.2.1

```
lspci -k

00:02.0 Display controller: Intel Corporation CometLake-S GT2 [UHD Graphics 630] (rev 05)
	DeviceName: Onboard - Video
	Subsystem: Dell CometLake-S GT2 [UHD Graphics 630]
	Kernel driver in use: vfio-pci
	Kernel modules: i915

cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-6.2.0-32-generic root=UUID=xxx ro kvm.ignore_msrs=1 intel_iommu=on vfio_iommu_type1.allow_unsafe_interrupts=1 iommu=pt vfio-pci.ids=8086:9bc5,8086:06c8 i915.enable_gvt=1 i915.enable_guc=0
```

### Qemu command
*If you used one of the included scripts, just note that*
```
mkdir i915dev
cd i915dev
wget https://github.com/patmagauran/i915ovmfPkg/releases/download/V0.2.1/ReleaseV0.2.1.zip
unzip ReleaseV0.2.1.zip
cd Release
dd if=/dev/zero of=disk bs=128M count=1
sudo mkfs.vfat disk
mkdir i915_simple
cp disk i915_simple/
cp /usr/share/OVMF/OVMF_CODE.fd .

# vim change  test-gvt-d.sh
sudo ./test-gvt-d.sh
```

<details markdown="1">
  <summary>test-gvt-d.sh</summary>
  <br>
<code>
#!/bin/bash
export WORKSPACE=/xxx/i915dev/Release
export PCILOC=0000:00:02.0
export PCIID=8086:9bca
cd $WORKSPACE
cd ./i915_simple
# Create an UEFI disk that immediately shuts down the VM when booted
mkdir -p tmpfat
mount disk tmpfat
mkdir -p tmpfat/EFI/BOOT
umount tmpfat
rmdir tmpfat
timeout --foreground -k 1 8 qemu-system-x86_64 -k en-us -name uefitest,debug-threads=on -nographic -vga none -chardev stdio,id=char0,logfile=serial.log,signal=off \
  -serial chardev:char0 -m 2048 -M pc -cpu host -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -machine kernel_irqchip=on -nodefaults -rtc base=localtime,driftfix=slew -no-hpet -global kvm-pit.lost_tick_policy=discard -enable-kvm -bios $WORKSPACE/OVMF_CODE.fd -device vfio-pci,host=$PCILOC,romfile=`pwd`/i915ovmf.rom -device qemu-xhci,p2=8,p3=8 -device usb-kbd -device usb-tablet -drive format=raw,file=disk -usb 
</code>
</details>

### Logs

**Full Log of VM**(From the time you run the qemu command until it exits)

**Anything in dmesg/syslog**

**Anything else you have found**

**Comment by HouQiming** [comment]
You need to provide your display resolution / refresh rate, or better, the
entire EDID (you can find that somewhere in /sys on the host). This
happened to me too during the initial development when the pixel clock id
was wrong, never figured out why. My old comment `//hack: anything else
hangs` meant a host hang.

**Comment by kimown** [comment]
@HouQiming 
My monitor is dell U2720Q, here is EDID data.
[DEL41B3.zip](https://github.com/patmagauran/i915ovmfPkg/files/12923736/DEL41B3.zip)

**Comment by patmagauran** [comment]
I am archiving this repository and no longer offer support as the owner. Please see the discord for support: https://discord.gg/bGNgmmYcWb
