### ISSUE TITLE
i915ovmf crashes Proxmox 7.4 with 6.1 kernel

### ISSUE THREAD

**Issue by wrobelda** [patmagauran/i915ovmfPkg#43]
**FIRST** Have you tried with the included scripts? Can you do regular vfio passthrough? Is there a clearly printed error? 

Have you Looked at https://github.com/RotatingFans/i915ovmfPkg/wiki/Having-Problems%3F

### Description

I am reporting an issue with Proxmox 7.4 with 6.1 kernel, which seems to be quite commonly reported now, namely the i915ovmf you provide crashes the whole host system. See e.g.:
https://forum.proxmox.com/threads/igpu-passthrough-fully-works-in-ubuntu-works-but-no-actual-hdmi-output-in-windows.127723/#post-558399

### System Info

- Host OS(Distro/Version): Proxmox 7.4
- CPU: Intel i5-10500T
- Any other GPUs: No
- Guest OS: not important
- GVT-G or GVT-D: GVT-D
- Display connections: a 4k projector over HDMI
- i915ovmfPkg Release version or Commit: V0.2.1

### Qemu command

Using `test-get-d.sh` from most recent release distribution.

### Logs

```
./test-gvt-d.sh: line 17: echo: write error: Invalid argument
Driver starts!
i915: found device 8086-9BC8 0
i915: start
i915: set pci attrs
i915: made gop path
i915: installed child handle
i915: before QEMU shenanigans
i915: vbt: 0x7FBFD400, bdb: 0x7FBFD430, sig: $B KLK    d0��0, bsig: BO_AABOK�t�
i915: finding section 2
i915: Boot display type: 0x0000
i915: Child device size: 39
i915: Child device count: 8
i915: SetupOpRegion: OpRegion @ 0x7FBFD000 size 0x2000 in 2 pages
i915: SetupFwcfgStuff returns 0
i915: after QEMU shenanigans
Port A VBT info: CRT:0 DVI:0 HDMI:0 DP:0 eDP:0 USB-Type-C:0 TBT:0 type:0000
VBT HDMI level shift for port A: 0
VBT DP max link rate for port A: 810000
Port B VBT info: CRT:0 DVI:16 HDMI:1 DP:4 eDP:0 USB-Type-C:0 TBT:0 type:60D6
VBT HDMI level shift for port B: 10
VBT DP max link rate for port B: 810000
Port C VBT info: CRT:0 DVI:16 HDMI:1 DP:4 eDP:0 USB-Type-C:0 TBT:0 type:60D6
VBT HDMI level shift for port C: 10
VBT DP max link rate for port C: 810000
Port D VBT info: CRT:0 DVI:16 HDMI:1 DP:0 eDP:0 USB-Type-C:0 TBT:0 type:60D2
VBT HDMI level shift for port D: 8
VBT DP max link rate for port D: 810000
Port E VBT info: CRT:0 DVI:0 HDMI:0 DP:0 eDP:0 USB-Type-C:0 TBT:0 type:0000
VBT HDMI level shift for port E: 0
VBT DP max link rate for port E: 810000
More than one child device for port A in VBT, using the first.
More than one child device for port A in VBT, using the first.
More than one child device for port A in VBT, using the first.
i915: power well enabled F00003AB
panel power sequencer register settings: PP_ON #x, PP_OFF #x, PP_DIV #x
PP_CTL:  00000000, PP_STAT  00000000
PP_CTL:  00000043, PP_STAT  0000000A
PP_CTL:  00000043, PP_STAT  80000008
i915: CDCLK = 0C000544
i915: DBUF timeout
i915: _PLclient_loop: send disconnect: Broken pipe
```

As a side note, the `line 17: echo: write error: Invalid argument` is `echo $PCILOC> /sys/bus/pci/devices/$PCILOC/driver/unbind`, where `$PCILOC` in the script is formatted as `vendor:id` (with a colon), meanwhile the sys interface apparently expects them space-separated, see https://www.ibm.com/docs/en/linux-on-systems?topic=hs-pci-2. Regardless, this is not important, since I am passing the id in `vfio-pci.ids=8086:9bc8` kernel cmd line and manually issuing the echo with space-separated `vendor id` returns `write error: File exists`, as expected.

**Anything in dmesg/syslog**

**Anything else you have found**

FYI, I can pass the GPU just fine using this very Proxmox host to a Debian guest VM. I am not doing anything exceptional here, have it configured with OVMF BIOS, i440fx machine, have iGPU's PCI device passed through with "All Functions", "ROM-Bar" and "Primary GPU" options checked. It doesn't, expectedly, display anything until the frame buffer is initialized by the operating system itself.

**Comment by wrobelda** [comment]
I also tested using 5.19 Proxmox' kernel, also crashes:
```
Driver starts!
i915: found device 8086-9BC8 0
i915: start
i915: set pci attrs
i915: made gop path
i915: installed child handle
i915: before QEMU shenanigans
i915: vbt: 0x7FBFD400, bdb: 0x7FBFD430, sig: $B KLK    d0��0, bsig: BO_AABOK�t�
i915: finding section 2
i915: Boot display type: 0x0000
i915: Child device size: 39
i915: Child device count: 8
i915: SetupOpRegion: OpRegion @ 0x7FBFD000 size 0x2000 in 2 pages
i915: SetupFwcfgStuff returns 0
i915: after QEMU shenanigans
Port A VBT info: CRT:0 DVI:0 HDMI:0 DP:0 eDP:0 USB-Type-C:0 TBT:0 type:0000
VBT HDMI level shift for port A: 0
VBT DP max link rate for port A: 810000
Port B VBT info: CRT:0 DVI:16 HDMI:1 DP:4 eDP:0 USB-Type-C:0 TBT:0 type:60D6
VBT HDMI level shift for port B: 10
VBT DP max link rate for port B: 810000
Port C VBT info: CRT:0 DVI:16 HDMI:1 DP:4 eDP:0 USB-Type-C:0 TBT:0 type:60D6
VBT HDMI level shift for port C: 10
VBT DP max link rate for port C: 810000
Port D VBT info: CRT:0 DVI:16 HDMI:1 DP:0 eDP:0 USB-Type-C:0 TBT:0 type:60D2
VBT HDMI level shift for port D: 8
VBT DP max link rate for port D: 810000
Port E VBT info: CRT:0 DVI:0 HDMI:0 DP:0 eDP:0 USB-Type-C:0 TBT:0 type:0000
VBT HDMI level shift for port E: 0
VBT DP max link rate for port E: 810000
More than one child device for port A in VBT, using the first.
More than one child device for port A in VBT, using the first.
More than one child device for port A in VBT, using the first.
i915: power well enabled F00003AB
panel power sequencer register settings: PP_ON #x, PP_OFF #x, PP_DIV #x
PP_CTL:  00000000, PP_STAT  00000000
PP_CTL:  00000043, PP_STAT  9000000A
PP_CTL:  00000043, PP_STAT  80000008
i915: CDCLK = 0C0005client_loop: send disconnect: Broken pipe
```

**Comment by patmagauran** [comment]
I am archiving this repository and no longer offer support as the owner. Please see the discord for support: https://discord.gg/bGNgmmYcWb
