### ISSUE TITLE
What is the difference between your rom file and the one mentioned in the Arch Wiki

### ISSUE THREAD

**Issue by mystiquewolf** [patmagauran/i915ovmfPkg#7]
Hi! What exactly is the difference between your rom file and the one mentioned in the [Arch Wiki](https://wiki.archlinux.org/index.php/Intel_GVT-g#Using_DMA-BUF_with_UEFI/OVMF)?

It's apparently taken from [THIS](https://www.reddit.com/r/VFIO/comments/av736o/creating_a_clover_bios_nonuefi_install_for_qemu/ehdz6mf/) Reddit post.

**Comment by RotatingFans** [comment]
I do not exactly know the difference for the gvt-g side of things. However, my version also implements gvt-d. This allows for full passthrough, instead of the virtual passthrough. I believe it also simplifies things for gvt-g displays(but this was the work of @HouQuiming)

**Comment by HouQiming** [comment]
The main difference is adding a UEFI GOP boot display (before OS driver
loads), for both gvt-d / gvt-g. Being very close to real hardware, the
gvt-g support only required adding a few lines on top of my HDMI monitor
code.

A boot display lets you see Windows recovery / disk checking interfaces. It
also seems to let Mac install.

**Comment by mystiquewolf** [comment]
So am i correct that both provide OpRegion to be used by the guest OS, and yours provides in addition a replacement for ramfb? The Arch Linux Wiki says that if ramfb is enabled, it _will_ show "POST, the firmware interface, and the guest initialization".

If the above is correct, what is the reason for replacing ramfb? I am not an expert in BIOS/UEFI, just researching.

**Comment by HouQiming** [comment]
Well, ramfb is like plugging in an additional monitor just for booting. It
works if you just need a quick chkdsk /f, but:

- You can't display ramfb content on your igpu-connected monitor if you're
using GVT-d, big problem if it's your only monitor
- Ramfb working doesn't indicate a working GVT setup. It's possible to work
in a guest for extended periods of time before realizing you've been
ramfb-ing all the way.
